"""Flatten the instruction parts into the one file the agent's runtime reads (CLAUDE.md, GEMINI.md,
AGENTS.md...). Not every harness expands @file imports, so the kit never relies on them."""
import re
from pathlib import Path

INCLUDE_RE = re.compile(r"^<!-- include: ([\w.\-]+) -->$")
HEADER = ("<!-- Generated by build-instructions.py from instructions.md and the files it includes. "
          "Edit those parts, not this file. -->\n\n")


def flatten(agent_dir, source="instructions.md") -> str:
    agent_dir = Path(agent_dir)
    out = []
    for line in (agent_dir / source).read_text(encoding="utf-8").splitlines(keepends=True):
        m = INCLUDE_RE.match(line.strip())
        if m:
            part = (agent_dir / m.group(1)).read_text(encoding="utf-8")
            out.append(part if part.endswith("\n") else part + "\n")
        else:
            out.append(line)
    return "".join(out)


def build(agent_dir, instructions_file) -> Path:
    path = Path(agent_dir) / instructions_file
    path.write_text(HEADER + flatten(agent_dir), encoding="utf-8", newline="\n")
    return path
