import pytest

from vfkit.instructions import build, flatten


def test_flatten_includes(tmp_path):
    (tmp_path / "instructions.md").write_text("# Top\n<!-- include: a.md -->\nend\n", encoding="utf-8")
    (tmp_path / "a.md").write_text("A body\n", encoding="utf-8")
    assert flatten(tmp_path) == "# Top\nA body\nend\n"


def test_missing_part_raises(tmp_path):
    (tmp_path / "instructions.md").write_text("<!-- include: gone.md -->\n", encoding="utf-8")
    with pytest.raises(FileNotFoundError):
        flatten(tmp_path)


def test_build_writes_header(tmp_path):
    (tmp_path / "instructions.md").write_text("body\n", encoding="utf-8")
    out = build(tmp_path, "AGENTS.md")
    text = out.read_text(encoding="utf-8")
    assert out.name == "AGENTS.md"
    assert text.startswith("<!-- Generated by build-instructions.py")
    assert text.endswith("body\n")
